# -*- coding: utf-8 -*-
"""SupervisedLearning_Project_4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tLrSZyNSqih4YSJnj5ALh2fd8Msnuk7O
"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score

# 1. Load dataset
df = pd.read_csv("project_4_spam.csv", encoding="latin-1")[["v1", "v2"]]
df.columns = ["label", "message"]

# Convert labels to binary
df["label"] = df["label"].map({"ham": 0, "spam": 1})

# 2. Split data
X_train, X_test, y_train, y_test = train_test_split(df["message"], df["label"], test_size=0.2, random_state=42)

# 3. Vectorize text
vectorizer = TfidfVectorizer(stop_words="english")
X_train_vec = vectorizer.fit_transform(X_train)
X_test_vec = vectorizer.transform(X_test)

# 4. Train model
model = MultinomialNB()
model.fit(X_train_vec, y_train)

# 5. Evaluate
y_pred = model.predict(X_test_vec)
print("Accuracy:", accuracy_score(y_test, y_pred))

# 6. User input
user_msg = input("Enter a message: ")
user_vec = vectorizer.transform([user_msg])
prediction = model.predict(user_vec)[0]

if prediction == 1:
    print("🚨 This message is Spam")
else:
    print("✅ This message is Ham")